# Generated by Django 5.2.17 on 2026-08-17 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['user', 'spent_on'], name='tracking_ti_user_id_7a8782_idx'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['task', 'spent_on'], name='tracking_ti_task_id_4008fb_idx'),
        ),
    ]
