# Generated by Django 5.2.17 on 2026-08-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['name']},
        ),
        migrations.RemoveConstraint(
            model_name='task',
            name='one_uncategorized_per_project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_uncategorized',
        ),
        migrations.AddField(
            model_name='project',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
